import img1 from "./Caraousel/1.jpg";
import img2 from "./Caraousel/2.jpg";
import img3 from "./Caraousel/3.jpg";
import img4 from "./Caraousel/4.jpg";
import img5 from "./Caraousel/5.jpg";
import img6 from "./Caraousel/6.jpg";
import img7 from "./Caraousel/7.jpg";
import img8 from "./Caraousel/8.jpg";
import img9 from "./Caraousel/9.jpg";
import img10 from "./Caraousel/10.jpg";
import img11 from "./Caraousel/11.jpg";
import img12 from "./Caraousel/12.png";
import img13 from "./Caraousel/13.jpg";
import img14 from "./Caraousel/14.jpg";
import img15 from "./Caraousel/15.jpg";
import img16 from "./Caraousel/16.jpg";
import img17 from "./Caraousel/17.jpg";
import img18 from "./Caraousel/18.jpg";
import img19 from "./Caraousel/19.jpg";
import img20 from "./Caraousel/20.jpg";
import img21 from "./Caraousel/21.jpg";
import img22 from "./Caraousel/22.jpg";
import img23 from "./Caraousel/23.jpg";
import img24 from "./Caraousel/24.jpg";
import img25 from "./Caraousel/25.jpg";
import img26 from "./Caraousel/26.jpg";
import img27 from "./Caraousel/27.jpg";
import img28 from "./Caraousel/28.jpg";
import img29 from "./Caraousel/29.jpg";
import img30 from "./Caraousel/30.jpg";
export const CarData = [
  {
    id:1,
    name: "Maruti 800 AC",
    year: 2007,
    selling_price: 60000,
    img: img1,
    km_driven: 70000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:2,
    name: "Maruti Wagon R LXI Minor",
    year: 2007,
    selling_price: 135000,
    img: img2,
    km_driven: 50000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:3,
    name: "Hyundai Verna 1.6 SX",
    year: 2012,
    selling_price: 600000,
    img: img3,
    km_driven: 100000,
    fuel: "Diesel",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:4,
    name: "Datsun RediGO T Option",
    year: 2017,
    selling_price: 250000,
    img: img4,
    km_driven: 46000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:5,
    name: "Honda Amaze VX i-DTEC",
    year: 2014,
    selling_price: 450000,
    img: img5,
    km_driven: 141000,
    fuel: "Diesel",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "Second Owner",
  },
  {
    id:6,
    name: "Maruti Alto LX BSIII",
    year: 2007,
    selling_price: 140000,
    img: img6,
    km_driven: 125000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:7,
    name: "Hyundai Xcent 1.2 Kappa S",
    year: 2016,
    selling_price: 550000,
    img: img7,
    km_driven: 25000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:8,
    name: "Tata Indigo Grand Petrol",
    year: 2014,
    selling_price: 240000,
    img: img8,
    km_driven: 60000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "Second Owner",
  },
  {
    id:9,
    name: "Hyundai Creta 1.6 VTVT S",
    year: 2015,
    selling_price: 850000,
    img: img9,
    km_driven: 25000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:10,
    name: "Maruti Celerio Green VXI",
    year: 2017,
    selling_price: 365000,
    img: img10,
    km_driven: 78000,
    fuel: "CNG",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:11,
    name: "Chevrolet Sail 1.2 Base",
    year: 2015,
    selling_price: 260000,
    img: img11,
    km_driven: 35000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:12,
    name: "Tata Indigo Grand Petrol",
    year: 2014,
    selling_price: 250000,
    img: img12,
    km_driven: 100000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:13,
    name: "Toyota Corolla Altis 1.8 VL CVT",
    year: 2018,
    selling_price: 1650000,
    img: img13,
    km_driven: 25000,
    fuel: "Petrol",
    seller_type: "Dealer",
    transmission: "Automatic",
    owner: "First Owner",
  },
  {
    id:14,
    name: "Maruti 800 AC",
    year: 2007,
    selling_price: 60000,
    img: img14,
    km_driven: 70000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:15,
    name: "Maruti Wagon R LXI Minor",
    year: 2007,
    selling_price: 135000,
    img: img15,
    km_driven: 50000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:16,
    name: "Hyundai Verna 1.6 SX",
    year: 2012,
    selling_price: 600000,
    img: img16,
    km_driven: 100000,
    fuel: "Diesel",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:17,
    name: "Datsun RediGO T Option",
    year: 2017,
    selling_price: 250000,
    img: img17,
    km_driven: 46000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:18,
    name: "Honda Amaze VX i-DTEC",
    year: 2014,
    selling_price: 450000,
    img: img18,
    km_driven: 141000,
    fuel: "Diesel",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "Second Owner",
  },
  {
    id:19,
    name: "Maruti Alto LX BSIII",
    year: 2007,
    selling_price: 140000,
    img: img19,
    km_driven: 125000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  {
    id:20,
    name: "Hyundai Xcent 1.2 Kappa S",
    year: 2016,
    selling_price: 550000,
    img: img20,
    km_driven: 25000,
    fuel: "Petrol",
    seller_type: "Individual",
    transmission: "Manual",
    owner: "First Owner",
  },
  // { id:21,
  //   name: "Tata Indigo Grand Petrol",
  //   year: 2014,
  //   selling_price: 240000,
  //   img: img21,
  //   km_driven: 60000,
  //   fuel: "Petrol",
  //   seller_type: "Individual",
  //   transmission: "Manual",
  //   owner: "Second Owner",
  // },
  // {
  //   "name": "Hyundai Creta 1.6 VTVT S",
  //   "year": 2015,
  //   "selling_price": 850000,
  //  img:img,
  //   "km_driven": 25000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Celerio Green VXI",
  //   "year": 2017,
  //   "selling_price": 365000,
  //   "km_driven": 78000,
  //   "fuel": "CNG",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Chevrolet Sail 1.2 Base",
  //   "year": 2015,
  //   "selling_price": 260000,
  //   "km_driven": 35000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Tata Indigo Grand Petrol",
  //   "year": 2014,
  //   "selling_price": 250000,
  //   "km_driven": 100000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Toyota Corolla Altis 1.8 VL CVT",
  //   "year": 2018,
  //   "selling_price": 1650000,
  //   "km_driven": 25000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Ciaz VXi Plus",
  //   "year": 2015,
  //   "selling_price": 585000,
  //   "km_driven": 24000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai Venue SX Opt Diesel",
  //   "year": 2019,
  //   "selling_price": 1195000,
  //   "km_driven": 5000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Chevrolet Enjoy TCDi LTZ 7 Seater",
  //   "year": 2013,
  //   "selling_price": 390000,
  //   "km_driven": 33000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Jaguar XF 2.2 Litre Luxury",
  //   "year": 2014,
  //   "selling_price": 1964999,
  //   "km_driven": 28000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mercedes-Benz New C-Class 220 CDI AT",
  //   "year": 2013,
  //   "selling_price": 1425000,
  //   "km_driven": 59000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Vitara Brezza ZDi Plus AMT",
  //   "year": 2018,
  //   "selling_price": 975000,
  //   "km_driven": 4500,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Audi Q5 2.0 TDI",
  //   "year": 2011,
  //   "selling_price": 1190000,
  //   "km_driven": 175900,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Honda City V MT",
  //   "year": 2018,
  //   "selling_price": 930000,
  //   "km_driven": 14500,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Tata Tigor 1.2 Revotron XT",
  //   "year": 2018,
  //   "selling_price": 525000,
  //   "km_driven": 15000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Audi A6 2.0 TDI  Design Edition",
  //   "year": 2013,
  //   "selling_price": 1735000,
  //   "km_driven": 50000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mercedes-Benz New C-Class C 220 CDI Avantgarde",
  //   "year": 2012,
  //   "selling_price": 1375000,
  //   "km_driven": 33800,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Skoda Superb Ambition 2.0 TDI CR AT",
  //   "year": 2011,
  //   "selling_price": 450000,
  //   "km_driven": 130400,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Toyota Corolla Altis G AT",
  //   "year": 2016,
  //   "selling_price": 900000,
  //   "km_driven": 50000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Toyota Innova 2.5 G (Diesel) 7 Seater",
  //   "year": 2015,
  //   "selling_price": 1300000,
  //   "km_driven": 80000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Jeep Compass 1.4 Sport Plus BSIV",
  //   "year": 2019,
  //   "selling_price": 1400000,
  //   "km_driven": 10000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mercedes-Benz E-Class E 200 CGI Elegance",
  //   "year": 2010,
  //   "selling_price": 850000,
  //   "km_driven": 119000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai i10 Magna 1.1L",
  //   "year": 2014,
  //   "selling_price": 229999,
  //   "km_driven": 60000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Fourth & Above Owner"
  // },
  // {
  //   "name": "BMW 3 Series 320d Sport Line",
  //   "year": 2013,
  //   "selling_price": 1550000,
  //   "km_driven": 75800,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Audi Q7 35 TDI Quattro Premium",
  //   "year": 2009,
  //   "selling_price": 1250000,
  //   "km_driven": 78000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "Third Owner"
  // },
  // {
  //   "name": "Hyundai Elantra CRDi S",
  //   "year": 2012,
  //   "selling_price": 625000,
  //   "km_driven": 40000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mahindra Scorpio 1.99 S10",
  //   "year": 2014,
  //   "selling_price": 1050000,
  //   "km_driven": 50000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Honda City i DTEC V",
  //   "year": 2014,
  //   "selling_price": 560000,
  //   "km_driven": 74000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Maruti Wagon R VXI BS IV with ABS",
  //   "year": 2014,
  //   "selling_price": 290000,
  //   "km_driven": 64000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Maruti Wagon R VXI BS IV",
  //   "year": 2012,
  //   "selling_price": 275000,
  //   "km_driven": 60000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Mahindra Scorpio LX",
  //   "year": 2009,
  //   "selling_price": 411000,
  //   "km_driven": 120000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Hyundai Santro Xing GLS",
  //   "year": 2009,
  //   "selling_price": 150000,
  //   "km_driven": 79000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Third Owner"
  // },
  // {
  //   "name": "Hyundai Grand i10 1.2 Kappa Asta",
  //   "year": 2019,
  //   "selling_price": 500000,
  //   "km_driven": 15000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Alto LXi",
  //   "year": 2006,
  //   "selling_price": 100000,
  //   "km_driven": 80000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Swift Dzire VDI Optional",
  //   "year": 2017,
  //   "selling_price": 725000,
  //   "km_driven": 18500,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Eeco 5 Seater AC BSIV",
  //   "year": 2018,
  //   "selling_price": 401000,
  //   "km_driven": 10200,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai i20 Sportz 1.4 CRDi",
  //   "year": 2018,
  //   "selling_price": 750000,
  //   "km_driven": 29000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Omni Maruti Omni MPI STD BSIII 5-STR W/ IMMOBILISER",
  //   "year": 2018,
  //   "selling_price": 310000,
  //   "km_driven": 28000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Swift ZDi BSIV",
  //   "year": 2016,
  //   "selling_price": 665000,
  //   "km_driven": 46000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai i20 2015-2017 Sportz Option 1.4 CRDi",
  //   "year": 2014,
  //   "selling_price": 465000,
  //   "km_driven": 70000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Alto LXi",
  //   "year": 2012,
  //   "selling_price": 160000,
  //   "km_driven": 60000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Mahindra Jeep CL 500 MDI",
  //   "year": 1996,
  //   "selling_price": 250000,
  //   "km_driven": 35000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Honda City i DTEC VX",
  //   "year": 2014,
  //   "selling_price": 675000,
  //   "km_driven": 90000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Wagon R VXI BS IV",
  //   "year": 2013,
  //   "selling_price": 300000,
  //   "km_driven": 80000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Tata Indica DLS",
  //   "year": 2005,
  //   "selling_price": 70000,
  //   "km_driven": 80000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai EON Magna Plus",
  //   "year": 2014,
  //   "selling_price": 240000,
  //   "km_driven": 73300,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Toyota Etios GD",
  //   "year": 2014,
  //   "selling_price": 525000,
  //   "km_driven": 92000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Alto LXi",
  //   "year": 2009,
  //   "selling_price": 151000,
  //   "km_driven": 66764,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Maruti Alto LXi",
  //   "year": 2009,
  //   "selling_price": 140000,
  //   "km_driven": 100000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Chevrolet Tavera Neo LS B3 - 7(C) seats BSIII",
  //   "year": 2010,
  //   "selling_price": 280000,
  //   "km_driven": 350000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Toyota Corolla Altis Diesel D4DG",
  //   "year": 2011,
  //   "selling_price": 350000,
  //   "km_driven": 230000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mahindra Scorpio 1.99 S6 Plus",
  //   "year": 2017,
  //   "selling_price": 570000,
  //   "km_driven": 60000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai EON Magna Plus",
  //   "year": 2018,
  //   "selling_price": 300000,
  //   "km_driven": 31000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Tata Indigo Classic Dicor",
  //   "year": 2007,
  //   "selling_price": 100000,
  //   "km_driven": 39000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Toyota Innova 2.5 V Diesel 8-seater",
  //   "year": 2009,
  //   "selling_price": 500000,
  //   "km_driven": 120000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Third Owner"
  // },
  // {
  //   "name": "Tata Indica Vista Quadrajet LS",
  //   "year": 2014,
  //   "selling_price": 125000,
  //   "km_driven": 166000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Fourth & Above Owner"
  // },
  // {
  //   "name": "Maruti Swift 1.3 VXi",
  //   "year": 2006,
  //   "selling_price": 130000,
  //   "km_driven": 110000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Third Owner"
  // },
  // {
  //   "name": "Ford EcoSport 1.5 Diesel Titanium BSIV",
  //   "year": 2017,
  //   "selling_price": 925000,
  //   "km_driven": 35000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Maruti Ciaz 1.3 Delta",
  //   "year": 2018,
  //   "selling_price": 750000,
  //   "km_driven": 60000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Honda Civic 1.8 V AT",
  //   "year": 2007,
  //   "selling_price": 200000,
  //   "km_driven": 54000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Automatic",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Hyundai i10 Sportz 1.2",
  //   "year": 2010,
  //   "selling_price": 248000,
  //   "km_driven": 63000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Skoda Rapid 1.5 TDI Elegance",
  //   "year": 2014,
  //   "selling_price": 450000,
  //   "km_driven": 120000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Hyundai Getz GLS",
  //   "year": 2005,
  //   "selling_price": 80000,
  //   "km_driven": 120000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Third Owner"
  // },
  // {
  //   "name": "Nissan Terrano XL",
  //   "year": 2014,
  //   "selling_price": 650000,
  //   "km_driven": 76000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Hyundai Grand i10 CRDi Sportz",
  //   "year": 2015,
  //   "selling_price": 450000,
  //   "km_driven": 80000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai Elite i20 Diesel Era",
  //   "year": 2019,
  //   "selling_price": 650000,
  //   "km_driven": 25000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Honda Amaze S i-VTEC",
  //   "year": 2016,
  //   "selling_price": 495000,
  //   "km_driven": 11958,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Honda Brio S MT",
  //   "year": 2015,
  //   "selling_price": 371000,
  //   "km_driven": 20000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai Creta 1.6 SX Option",
  //   "year": 2017,
  //   "selling_price": 1025000,
  //   "km_driven": 9000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mercedes-Benz S-Class S 350d Connoisseurs Edition",
  //   "year": 2017,
  //   "selling_price": 8150000,
  //   "km_driven": 6500,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Mahindra XUV500 W8 2WD",
  //   "year": 2015,
  //   "selling_price": 750000,
  //   "km_driven": 70000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Renault Duster 85PS Diesel RxL Optional",
  //   "year": 2013,
  //   "selling_price": 600000,
  //   "km_driven": 120000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Hyundai Santro Xing XO",
  //   "year": 2007,
  //   "selling_price": 80000,
  //   "km_driven": 58000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Mahindra Bolero 2011-2019 SLE",
  //   "year": 2013,
  //   "selling_price": 325000,
  //   "km_driven": 62200,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Audi A6 2.0 TDI Premium Plus",
  //   "year": 2014,
  //   "selling_price": 1470000,
  //   "km_driven": 34000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Fiat Avventura MULTIJET Emotion",
  //   "year": 2015,
  //   "selling_price": 350000,
  //   "km_driven": 53000,
  //   "fuel": "Diesel",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Audi A8 4.2 TDI",
  //   "year": 2013,
  //   "selling_price": 2800000,
  //   "km_driven": 49000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Datsun RediGO 1.0 S",
  //   "year": 2017,
  //   "selling_price": 210000,
  //   "km_driven": 15000,
  //   "fuel": "Petrol",
  //   "seller_type": "Dealer",
  //   "transmission": "Manual",
  //   "owner": "Second Owner"
  // },
  // {
  //   "name": "Volkswagen Jetta 1.4 TSI Comfortline",
  //   "year": 2013,
  //   "selling_price": 450000,
  //   "km_driven": 50000,
  //   "fuel": "Petrol",
  //   "seller_type": "Individual",
  //   "transmission": "Manual",
  //   "owner": "First Owner"
  // },
  // {
  //   "name": "Audi A4 2.0 TDI 177 Bhp Premium Plus",
  //   "year": 2013,
  //   "selling_price": 1150000,
  //   "km_driven": 53000,
  //   "fuel": "Diesel",
  //   "seller_type": "Dealer",
  //   "transmission": "Automatic",
  //   "owner": "First Owner"
  // }
];
